version: '3.5'

services:
  nginx:
    image: nginx
    container_name: second_service_nginx
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
    expose:
      - "80"
    networks:
      - fmi

networks:
  default:
    name: second_service_network
  fmi:
    external: true